import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1c1b1b',
        'on-primary': '#ffffff',
        'inverse-primary': '#88d982',
        'on-primary-fixed': '#002204',
        'on-tertiary-container': '#e9f2ff',
        'on-tertiary-fixed': '#001d34',
        'inverse-on-surface': '#f3f0ef',
        'on-tertiary': '#ffffff',
        background: '#fcf9f8',
        'tertiary-container': '#0072b6',
        'on-primary-container': '#cbffc2',
        'on-secondary-fixed': '#261a00',
        'secondary-fixed': '#ffdf9e',
        'on-error': '#ffffff',
        'inverse-surface': '#313030',
        'secondary-fixed-dim': '#fabd00',
        'on-background': '#1c1b1b',
        surface: '#fcf9f8',
        secondary: '#785900',
        'on-surface-variant': '#40493d',
        outline: '#707a6c',
        'primary-fixed': '#a3f69c',
        'on-secondary': '#ffffff',
        'surface-variant': '#e5e2e1',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#f0edec',
        'on-primary-fixed-variant': '#005312',
        'surface-container-high': '#ebe7e7',
        'primary-container': '#2e7d32',
        'surface-tint': '#1b6d24',
        'surface-container-highest': '#e5e2e1',
        'on-secondary-container': '#6c5000',
        'surface-dim': '#dcd9d9',
        'primary-fixed-dim': '#88d982',
        'surface-container-low': '#f6f3f2',
        'secondary-container': '#fdc003',
        'on-secondary-fixed-variant': '#5b4300',
        tertiary: '#00598f',
        'tertiary-fixed-dim': '#99cbff',
        primary: '#0d631b',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'tertiary-fixed': '#cfe5ff',
        'on-tertiary-fixed-variant': '#004a78',
        'outline-variant': '#bfcaba',
        'surface-bright': '#fcf9f8',
        'on-error-container': '#93000a',
        // Fallback backward compatibility tokens
        bg: '#fcf9f8',
        border: '#bfcaba',
        'text-primary': '#1c1b1b',
        'text-muted': '#40493d',
        accent: '#0d631b',
        'accent-glow': '#fdc003',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-padding-desktop': '64px',
        gutter: '24px',
        unit: '8px',
        'section-gap': '80px',
        'container-padding-mobile': '16px',
      },
      fontFamily: {
        display: ['var(--font-playfair)', 'Playfair Display', 'serif'],
        body: ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        'label-lg': ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        'headline-md': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'headline-lg': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'display-lg': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'body-md': ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        'label-sm': ['var(--font-lexend)', 'Lexend', 'sans-serif'],
        'display-lg-mobile': ['var(--font-playfair)', 'Playfair Display', 'serif'],
        'body-lg': ['var(--font-lexend)', 'Lexend', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      screens: {
        xs: '480px',
      },
    },
  },
  plugins: [],
};

export default config;
